weekly_temperature = ((33, 34, 28), (24, 31, 27), (24, 23, 27), (28, 32, 34), (33, 21, 28), (20, 25, 31), (21, 31, 28))
monday, tuesday, wednesday, thursday, friday, saturday, sunday = weekly_temperature
monday_avg = sum(monday) / len(monday)
monday_min = min(monday)
monday_max = max(monday)
tuesday_avg = sum(tuesday) / len(tuesday)    
tuesday_min = min(tuesday)
tuesday_max = max(tuesday) 
wednesday_avg = sum(wednesday) / len(wednesday)    
wednesday_min = min(wednesday)
wednesday_max = max(wednesday)
thursday_avg = sum(thursday) / len(thursday)   
thursday_min = min(thursday)
thursday_max = max(thursday)
friday_avg = sum(friday) / len(friday)    
friday_min = min(friday)
friday_max = max(friday)
saturday_avg = sum(saturday) / len(saturday)   
saturday_min = min(saturday)
saturday_max = max(saturday) 
sunday_avg = sum(sunday) / len(sunday)
sunday_min = min(sunday)
sunday_max = max(sunday)
weekly_avg = (monday_avg + tuesday_avg + wednesday_avg + thursday_avg + friday_avg + saturday_avg + sunday_avg) / len(weekly_temperature)

print("Monday avg: ", monday_avg, "\nMonday min: ", monday_min, "\nMonday max: ", monday_max, "\n")
print("Tuesday avg: ", tuesday_avg, "\nTuesday min: ", tuesday_min, "\nTuesday max: ", tuesday_max, "\n")
print("Wednesday avg: ", wednesday_avg, "\nWednesday min: ", wednesday_min, "\nWednesday max: ", wednesday_max, "\n")
print("Thursday avg: ", thursday_avg, "\nThursday min: ", thursday_min, "\nThursday max: ", thursday_max, "\n")
print("Friday avg: ", friday_avg, "\nFriday min: ", friday_min, "\nFriday max: ", friday_max, "\n")
print("Saturday avg: ", saturday_avg, "\nSaturday min: ", saturday_min, "\nSaturday max: ", saturday_max, "\n")
print("Sunday avg: ", sunday_avg, "\nSunday min: ", sunday_min, "\nSunday max: ", sunday_max, "\n")
print("Weekly avg: ", weekly_avg, "\n")